### ISSUE TITLE
Setup search engine using elasticsearch and angularjs.

### ISSUE THREAD

**Issue by babukalamgi** [vivekkalyanarangan30/searchengine#3]
HI Vivek,

I am using your search engine using elasticsearch and angularjs.
I tried to configure the both the steps docker, native setup, But i am unable to

while i am opening localhost:9200 i can see only json data, where is the front-end with text box.

How to setup that can you give me some clear explanation please.

**Comment by vivekkalyanarangan30** [comment]
localhost:9200 is supposed to give you json response as that is where elasticsearch is deployed. For the UI with the textbox, simply use the port where Tomcat is installed! So typically Tomcat ports are 80 and 8080 - my best guess is localhost:80 or localhost:8080
